		%define S_Char int8_t
		%define U_Char uint8_t

		%define S_Short int16_t
		%define S_Short_Int int16_t
		%define U_Short uint16_t
		%define U_Short_Int uint16_t

		%define S_int   int32_t
		%define U_int   uint32_t

		%define S_Long  int32_t
		%define S_Long_Int int32_t
		%define U_Long  uint32_t
		%define U_Long_Int uint32_t

		%define S_LongLong int64_t
		%define S_LongLong_Int int64_t
		%define U_LongLong uint64_t
		%define U_LongLong_Int uint64_t

		%define size_t uint32_t

		%define SizeOfInt 4
		%define BitnessOfInt SizeOfInt*8

%define FREE_REG1_INTSIZE FREE_REG1_32
%define FREE_REG2_INTSIZE FREE_REG2_32
%define FREE_REG3_INTSIZE FREE_REG3_32
%define VOLATILE_REG1_INTSIZE VOLATILE_REG1_32






;DEFINING FREE REGISTERS FOR CURRENT SIZE OF POINTER
;AND SOME OTHER POINTER SIZE SPECIFIC REGISTERS(like esp, ebp)
	%define FREE_REG1_PTRSIZE FREE_REG1_32
	%define FREE_REG2_PTRSIZE FREE_REG2_32
	%define FREE_REG3_PTRSIZE FREE_REG3_32
	%define VOLATILE_REG1_PTRSIZE VOLATIVE_REG1_32

	%define AX_PTRSIZE eax
	%define BX_PTRSIZE ebx
	%define CX_PTRSIZE ecx
	%define DX_PTRSIZE edx
	%define SI_PTRSIZE esi
	%define DI_PTRSIZE edi
	%define BP_PTRSIZE ebp
	%define SP_PTRSIZE esp












;DEFINING ARGUMENTS LOCATION FOR CURRENT POINTER SIZE
    %define STACK_ARG1_SP [STACK_ARGX_SP_LEFT_TO_RIGHT(1, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG1_SP8 byte[STACK_ARGX_SP_LEFT_TO_RIGHT(1, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG1_SP16 word[STACK_ARGX_SP_LEFT_TO_RIGHT(1, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG1_SP32 dword[STACK_ARGX_SP_LEFT_TO_RIGHT(1, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%define STACK_ARG2_SP [STACK_ARGX_SP_LEFT_TO_RIGHT(2, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG2_SP8 byte[STACK_ARGX_SP_LEFT_TO_RIGHT(2, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG2_SP16 word[STACK_ARGX_SP_LEFT_TO_RIGHT(2, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG2_SP32 dword[STACK_ARGX_SP_LEFT_TO_RIGHT(2, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%define STACK_ARG3_SP [STACK_ARGX_SP_LEFT_TO_RIGHT(3, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG3_SP8 byte[STACK_ARGX_SP_LEFT_TO_RIGHT(3, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG3_SP16 word[STACK_ARGX_SP_LEFT_TO_RIGHT(3, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG3_SP32 dword[STACK_ARGX_SP_LEFT_TO_RIGHT(3, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%DEFINE STACK_ARG4_SP [STACK_ARGX_SP_LEFT_TO_RIGHT(4, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG4_SP8 byte[STACK_ARGX_SP_LEFT_TO_RIGHT(4, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG4_SP16 word[STACK_ARGX_SP_LEFT_TO_RIGHT(4, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG4_SP32 dword[STACK_ARGX_SP_LEFT_TO_RIGHT(4, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%DEFINE STACK_ARG5_SP [STACK_ARGX_SP_LEFT_TO_RIGHT(5, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG5_SP8 byte[STACK_ARGX_SP_LEFT_TO_RIGHT(5, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG5_SP16 word[STACK_ARGX_SP_LEFT_TO_RIGHT(5, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG5_SP32 dword[STACK_ARGX_SP_LEFT_TO_RIGHT(5, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%DEFINE STACK_ARG6_SP [STACK_ARGX_SP_LEFT_TO_RIGHT(6, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG6_SP8 byte[STACK_ARGX_SP_LEFT_TO_RIGHT(6, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG6_SP16 word[STACK_ARGX_SP_LEFT_TO_RIGHT(6, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG6_SP32 dword[STACK_ARGX_SP_LEFT_TO_RIGHT(6, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
    %define STACK_ARG7_SP [STACK_ARGX_SP_LEFT_TO_RIGHT(7, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG7_SP8 byte[STACK_ARGX_SP_LEFT_TO_RIGHT(7, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG7_SP16 word[STACK_ARGX_SP_LEFT_TO_RIGHT(7, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG7_SP32 dword[STACK_ARGX_SP_LEFT_TO_RIGHT(7, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]


	%DEFINE STACK_ARG1_BP [STACK_ARGX_BP_LEFT_TO_RIGHT(1, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG1_BP8 byte[STACK_ARGX_BP_LEFT_TO_RIGHT(1, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG1_BP16 word[STACK_ARGX_BP_LEFT_TO_RIGHT(1, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG1_BP32 dword[STACK_ARGX_BP_LEFT_TO_RIGHT(1, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%DEFINE STACK_ARG2_BP [STACK_ARGX_BP_LEFT_TO_RIGHT(2, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG2_BP8 byte[STACK_ARGX_BP_LEFT_TO_RIGHT(2, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG2_BP16 word[STACK_ARGX_BP_LEFT_TO_RIGHT(2, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG2_BP32 dword[STACK_ARGX_BP_LEFT_TO_RIGHT(2, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%DEFINE STACK_ARG3_BP [STACK_ARGX_BP_LEFT_TO_RIGHT(3, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG3_BP8 byte[STACK_ARGX_BP_LEFT_TO_RIGHT(3, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG3_BP16 word[STACK_ARGX_BP_LEFT_TO_RIGHT(3, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG3_BP32 dword[STACK_ARGX_BP_LEFT_TO_RIGHT(3, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%DEFINE STACK_ARG4_BP [STACK_ARGX_BP_LEFT_TO_RIGHT(4, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG4_BP8 byte[STACK_ARGX_BP_LEFT_TO_RIGHT(4, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG4_BP16 word[STACK_ARGX_BP_LEFT_TO_RIGHT(4, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG4_BP32 dword[STACK_ARGX_BP_LEFT_TO_RIGHT(4, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%DEFINE STACK_ARG5_BP [STACK_ARGX_BP_LEFT_TO_RIGHT(5, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG5_BP8 byte[STACK_ARGX_BP_LEFT_TO_RIGHT(5, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG5_BP16 word[STACK_ARGX_BP_LEFT_TO_RIGHT(5, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG5_BP32 dword[STACK_ARGX_BP_LEFT_TO_RIGHT(5, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
	%DEFINE STACK_ARG6_BP [STACK_ARGX_BP_LEFT_TO_RIGHT(6, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG6_BP8 byte[STACK_ARGX_BP_LEFT_TO_RIGHT(6, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG6_BP16 word[STACK_ARGX_BP_LEFT_TO_RIGHT(6, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG6_BP32 dword[STACK_ARGX_BP_LEFT_TO_RIGHT(6, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
    %define STACK_ARG7_BP [STACK_ARGX_BP_LEFT_TO_RIGHT(7, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG7_BP8 byte[STACK_ARGX_BP_LEFT_TO_RIGHT(7, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG7_BP16 word[STACK_ARGX_BP_LEFT_TO_RIGHT(7, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]
		%define STACK_ARG7_BP32 dword[STACK_ARGX_BP_LEFT_TO_RIGHT(7, NASM_DEF_MACRO_ACRGUMETNS_AMOUNT)]







;1-name 
;2-index
;3-optional argument amount
%macro NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_SP8 2-3
	%if %0=2
		%error NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_SP8
		%error YOU need to give arguments amount when using MS32 ABI
		%error You can always give arguments amount to this it will be safe
	%endif

	%define %[%1] byte[STACK_ARGX_SP_LEFT_TO_RIGHT((%2), (%3))]
%endmacro
%macro NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_SP16 2-3
	%if %0=2
		%error NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_SP16
		%error YOU need to give arguments amount when using MS32 ABI
		%error You can always give arguments amount to this it will be safe
	%endif
	
    %define %[%1] word[STACK_ARGX_SP_LEFT_TO_RIGHT((%2), (%3))]
%endmacro
%macro NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_SP32 2-3
	%if %0=2
		%error NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_SP32
		%error YOU need to give arguments amount when using MS32 ABI
		%error You can always give arguments amount to this it will be safe
	%endif
	
    %define %[%1] dword[STACK_ARGX_SP_LEFT_TO_RIGHT((%2), (%3))]
%endmacro
%macro NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_SP 2-3
	%if %0=2
		%error NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_SP
		%error YOU need to give arguments amount when using MS32 ABI
		%error You can always give arguments amount to this it will be safe
	%endif
	
    %define %[%1] [STACK_ARGX_SP_LEFT_TO_RIGHT((%2), (%3))]
%endmacro

;1-name 
;2-index
;3-optional argument amount
%macro NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_BP8 2-3
	%if %0=2
		%error NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_BP8
		%error YOU need to give arguments amount when using MS32 ABI
		%error You can always give arguments amount to this it will be safe
	%endif

	%define %[%1] byte[STACK_ARGX_BP_LEFT_TO_RIGHT((%2), (%3))]
%endmacro
%macro NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_BP16 2-3
	%if %0=2
		%error NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_BP16
		%error YOU need to give arguments amount when using MS32 ABI
		%error You can always give arguments amount to this it will be safe
	%endif
	
    %define %[%1] word[STACK_ARGX_BP_LEFT_TO_RIGHT((%2), (%3))]
%endmacro
%macro NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_BP32 2-3
    %if %0=2
	    %error NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_BP32
    	%error YOU need to give arguments amount when using MS32 ABI
	    %error You can always give arguments amount to this it will be safe
    %endif
	
    %define %[%1] dword[STACK_ARGX_BP_LEFT_TO_RIGHT((%2), (%3))]
%endmacro
%macro NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_BP 2-3
	%if %0=2
		%error NASM_DEFAULT_MACROSES_INTERNAL_MACRO_DEFINE_INT_STACK_ARGUMENT_BP
		%error YOU need to give arguments amount when using MS32 ABI
		%error You can always give arguments amount to this it will be safe
	%endif

	%define %[%1] [STACK_ARGX_BP_LEFT_TO_RIGHT((%2), (%3))]
%endmacro










%define LODS_INT lodsd
%define STOS_INT stosd
%define CMPS_INT cmpsd
%define MOVS_INT movsd